services:
  postgres:
    image: postgres:16
    pull_policy: missing
    environment:
      - POSTGRES_DB=ny_taxi
      - POSTGRES_USER=zoomcamp
      - POSTGRES_PASSWORD=zoomcamp
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4
    pull_policy: missing
    environment:
      - PGADMIN_DEFAULT_EMAIL=zoomcamp@zoomcamp.com
      - PGADMIN_DEFAULT_PASSWORD=zoomcamp
      - POSTGRES_DB=ny_taxi
    ports:
      - "8080:80"